first=int(input("Enter the first number"))
second=float(input("Enter the second number"))
print(f"The sum of {first} and {second} is= {first+second}")
print(f"The difference of {first} and {second} is ={first-second}")
print(f"The product of {first} and {second} is= {first*second}")
print(f"The quotient of {first} and {second} is ={first/second}")